# Data Wrangling

Load & transform NBA dataset

Ensure the two datasets are located in folder called data (or update load filepath)

In [3]:
import pandas as pd
import numpy as np

In [4]:
# Load raw csv data
df_shots = pd.read_csv("data/shotdetail_2024.csv")
df_cdnnba = pd.read_csv("data/cdnnba_2024.csv")
df_shots.head(10)

,GRID_TYPE,GAME_ID,GAME_EVENT_ID,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_NAME,PERIOD,MINUTES_REMAINING,SECONDS_REMAINING,...,SHOT_ZONE_AREA,SHOT_ZONE_RANGE,SHOT_DISTANCE,LOC_X,LOC_Y,SHOT_ATTEMPTED_FLAG,SHOT_MADE_FLAG,GAME_DATE,HTM,VTM
0,Shot Chart Detail,22400001,7,1642258,Zaccharie Risacher,1610612737,Atlanta Hawks,1,11,43,...,Left Side Center(LC),24+ ft.,26,-168,205,1,0,20241112,BOS,ATL
1,Shot Chart Detail,22400001,10,1630552,Jalen Johnson,1610612737,Atlanta Hawks,1,11,38,...,Left Side(L),8-16 ft.,13,-136,-1,1,0,20241112,BOS,ATL
2,Shot Chart Detail,22400001,21,1630552,Jalen Johnson,1610612737,Atlanta Hawks,1,10,50,...,Right Side Center(RC),24+ ft.,25,157,203,1,1,20241112,BOS,ATL
3,Shot Chart Detail,22400001,34,1630811,Keaton Wallace,1610612737,Atlanta Hawks,1,9,47,...,Left Side Center(LC),24+ ft.,25,-176,184,1,0,20241112,BOS,ATL
4,Shot Chart Detail,22400001,36,203991,Clint Capela,1610612737,Atlanta Hawks,1,9,44,...,Center(C),Less Than 8 ft.,2,-25,8,1,1,20241112,BOS,ATL
5,Shot Chart Detail,22400001,39,1642258,Zaccharie Risacher,1610612737,Atlanta Hawks,1,9,23,...,Center(C),Less Than 8 ft.,1,10,13,1,1,20241112,BOS,ATL
6,Shot Chart Detail,22400001,46,1642258,Zaccharie Risacher,1610612737,Atlanta Hawks,1,8,50,...,Center(C),8-16 ft.,12,53,111,1,0,20241112,BOS,ATL
7,Shot Chart Detail,22400001,48,1642258,Zaccharie Risacher,1610612737,Atlanta Hawks,1,8,47,...,Center(C),Less Than 8 ft.,1,-10,17,1,0,20241112,BOS,ATL
8,Shot Chart Detail,22400001,50,1642258,Zaccharie Risacher,1610612737,Atlanta Hawks,1,8,46,...,Center(C),Less Than 8 ft.,1,-10,1,1,0,20241112,BOS,ATL
9,Shot Chart Detail,22400001,52,1642258,Zaccharie Risacher,1610612737,Atlanta Hawks,1,8,43,...,Center(C),Less Than 8 ft.,0,0,0,1,0,20241112,BOS,ATL

In [5]:
df_shots.columns

Index(['GRID_TYPE', 'GAME_ID', 'GAME_EVENT_ID', 'PLAYER_ID', 'PLAYER_NAME',
       'TEAM_ID', 'TEAM_NAME', 'PERIOD', 'MINUTES_REMAINING',
       'SECONDS_REMAINING', 'EVENT_TYPE', 'ACTION_TYPE', 'SHOT_TYPE',
       'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'SHOT_DISTANCE',
       'LOC_X', 'LOC_Y', 'SHOT_ATTEMPTED_FLAG', 'SHOT_MADE_FLAG', 'GAME_DATE',
       'HTM', 'VTM'],
      dtype='object')

In [6]:
df_cdnnba.head(10)

,actionNumber,clock,timeActual,period,periodType,actionType,subType,qualifiers,personId,x,...,stealPersonId,pointsTotal,assistPlayerNameInitial,assistPersonId,assistTotal,foulPersonalTotal,foulTechnicalTotal,foulDrawnPlayerName,foulDrawnPersonId,gameId
0,2,PT12M00.00S,2024-11-13T00:10:24.900Z,1,REGULAR,period,start,NaN,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22400001
1,4,PT11M58.00S,2024-11-13T00:10:26.800Z,1,REGULAR,jumpball,recovered,NaN,1630811,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22400001
2,7,PT11M43.00S,2024-11-13T00:10:40Z,1,REGULAR,3pt,Jump Shot,NaN,1642258,27.414586,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22400001
3,8,PT11M43.00S,2024-11-13T00:10:40Z,1,REGULAR,block,NaN,NaN,1628369,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22400001
4,9,PT11M42.00S,2024-11-13T00:10:41Z,1,REGULAR,rebound,offensive,NaN,1642258,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22400001
5,10,PT11M38.00S,2024-11-13T00:10:46Z,1,REGULAR,2pt,Jump Shot,2ndchance,1630552,5.469777,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22400001
6,11,PT11M37.00S,2024-11-13T00:10:47Z,1,REGULAR,rebound,defensive,NaN,201143,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22400001
7,12,PT11M24.00S,2024-11-13T00:11:00.300Z,1,REGULAR,3pt,Jump Shot,NaN,1628401,71.172799,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22400001
8,13,PT11M22.00S,2024-11-13T00:11:02.300Z,1,REGULAR,rebound,defensive,NaN,1630552,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22400001
9,14,PT11M17.00S,2024-11-13T00:11:08.900Z,1,REGULAR,turnover,traveling,NaN,1630552,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22400001

In [7]:
df_cdnnba.columns

Index(['actionNumber', 'clock', 'timeActual', 'period', 'periodType',
       'actionType', 'subType', 'qualifiers', 'personId', 'x', 'y',
       'possession', 'scoreHome', 'scoreAway', 'edited', 'orderNumber',
       'isTargetScoreLastPeriod', 'xLegacy', 'yLegacy', 'isFieldGoal', 'side',
       'description', 'personIdsFilter', 'teamId', 'teamTricode', 'descriptor',
       'jumpBallRecoveredName', 'jumpBallRecoverdPersonId', 'playerName',
       'playerNameI', 'jumpBallWonPlayerName', 'jumpBallWonPersonId',
       'jumpBallLostPlayerName', 'jumpBallLostPersonId', 'area', 'areaDetail',
       'shotDistance', 'shotResult', 'blockPlayerName', 'blockPersonId',
       'shotActionNumber', 'reboundTotal', 'reboundDefensiveTotal',
       'reboundOffensiveTotal', 'officialId', 'turnoverTotal',
       'stealPlayerName', 'stealPersonId', 'pointsTotal',
       'assistPlayerNameInitial', 'assistPersonId', 'assistTotal',
       'foulPersonalTotal', 'foulTechnicalTotal', 'foulDrawnPlayerName',
       'foulDrawnPersonId', 'gameId'],
      dtype='object')

In [8]:

df_merged = pd.merge(df_shots, df_cdnnba, how='left', left_on=['GAME_ID', 'GAME_EVENT_ID'], right_on=['gameId', 'actionNumber'])
df_merged.head(10)

,GRID_TYPE,GAME_ID,GAME_EVENT_ID,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_NAME,PERIOD,MINUTES_REMAINING,SECONDS_REMAINING,...,stealPersonId,pointsTotal,assistPlayerNameInitial,assistPersonId,assistTotal,foulPersonalTotal,foulTechnicalTotal,foulDrawnPlayerName,foulDrawnPersonId,gameId
0,Shot Chart Detail,22400001,7,1642258,Zaccharie Risacher,1610612737,Atlanta Hawks,1,11,43,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22400001.0
1,Shot Chart Detail,22400001,10,1630552,Jalen Johnson,1610612737,Atlanta Hawks,1,11,38,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22400001.0
2,Shot Chart Detail,22400001,21,1630552,Jalen Johnson,1610612737,Atlanta Hawks,1,10,50,...,NaN,3.0,K. Wallace,1630811.0,1.0,NaN,NaN,NaN,NaN,22400001.0
3,Shot Chart Detail,22400001,34,1630811,Keaton Wallace,1610612737,Atlanta Hawks,1,9,47,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22400001.0
4,Shot Chart Detail,22400001,36,203991,Clint Capela,1610612737,Atlanta Hawks,1,9,44,...,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22400001.0
5,Shot Chart Detail,22400001,39,1642258,Zaccharie Risacher,1610612737,Atlanta Hawks,1,9,23,...,NaN,2.0,K. Wallace,1630811.0,2.0,NaN,NaN,NaN,NaN,22400001.0
6,Shot Chart Detail,22400001,46,1642258,Zaccharie Risacher,1610612737,Atlanta Hawks,1,8,50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22400001.0
7,Shot Chart Detail,22400001,48,1642258,Zaccharie Risacher,1610612737,Atlanta Hawks,1,8,47,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22400001.0
8,Shot Chart Detail,22400001,50,1642258,Zaccharie Risacher,1610612737,Atlanta Hawks,1,8,46,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22400001.0
9,Shot Chart Detail,22400001,52,1642258,Zaccharie Risacher,1610612737,Atlanta Hawks,1,8,43,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22400001.0

In [9]:
# Check merge correct

df_test = df_merged['TEAM_ID'] != df_merged['teamId']
df_test2 = df_merged['PLAYER_ID'] != df_merged['personId'] 

# Display Team ID discrepancies
df_merged[['TEAM_ID', 'teamId']][df_test]

           TEAM_ID  teamId
44436   1610612742     NaN
53316   1610612743     NaN
212843  1610612764     NaN

In [10]:
# Display Player ID discrepancies
df_merged[['PLAYER_ID', 'personId']][df_test2]

        PLAYER_ID   personId
27517     1641878  1641733.0
44436     1630702        NaN
53316      203999        NaN
107477    1642377  1630590.0
110718    1629639  1631107.0
131012    1629638  1630183.0
131013    1630183  1629638.0
133262    1642274  1629750.0
207388     203903  1631117.0
212843    1629673        NaN

In [12]:
# Convert to date data type
df_merged['GAME_DATE'] = pd.to_datetime(df_merged['GAME_DATE'], format="%Y%m%d")

# Home - 
df_merged['SCORE_MARGIN'] = df_merged['scoreHome'] - df_merged['scoreAway']

# Convert to based on player taking actions perspective
df_merged['MARGIN_ACTION'] = np.where(df_merged['teamTricode'] == df_merged['HTM'], df_merged['SCORE_MARGIN'], df_merged['SCORE_MARGIN']*-1)

In [14]:
# Drop redundant columns

df_merged.drop(['actionNumber', 'period'], axis=1)

,GRID_TYPE,GAME_ID,GAME_EVENT_ID,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_NAME,PERIOD,MINUTES_REMAINING,SECONDS_REMAINING,...,assistPlayerNameInitial,assistPersonId,assistTotal,foulPersonalTotal,foulTechnicalTotal,foulDrawnPlayerName,foulDrawnPersonId,gameId,SCORE_MARGIN,MARGIN_ACTION
0,Shot Chart Detail,22400001,7,1642258,Zaccharie Risacher,1610612737,Atlanta Hawks,1,11,43,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22400001.0,0.0,-0.0
1,Shot Chart Detail,22400001,10,1630552,Jalen Johnson,1610612737,Atlanta Hawks,1,11,38,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22400001.0,0.0,-0.0
2,Shot Chart Detail,22400001,21,1630552,Jalen Johnson,1610612737,Atlanta Hawks,1,10,50,...,K. Wallace,1630811.0,1.0,NaN,NaN,NaN,NaN,22400001.0,-3.0,3.0
3,Shot Chart Detail,22400001,34,1630811,Keaton Wallace,1610612737,Atlanta Hawks,1,9,47,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22400001.0,0.0,-0.0
4,Shot Chart Detail,22400001,36,203991,Clint Capela,1610612737,Atlanta Hawks,1,9,44,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22400001.0,-2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219522,Shot Chart Detail,22401217,643,1629673,Jordan Poole,1610612764,Washington Wizards,4,3,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22401217.0,-15.0,-15.0
219523,Shot Chart Detail,22401217,646,1629673,Jordan Poole,1610612764,Washington Wizards,4,2,53,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22401217.0,-18.0,-18.0
219524,Shot Chart Detail,22401217,661,1642259,Alex Sarr,1610612764,Washington Wizards,4,2,11,...,B. Coulibaly,1641731.0,6.0,NaN,NaN,NaN,NaN,22401217.0,-18.0,-18.0
219525,Shot Chart Detail,22401217,668,1630551,Justin Champagnie,1610612764,Washington Wizards,4,1,45,...,J. Poole,1629673.0,7.0,NaN,NaN,NaN,NaN,22401217.0,-16.0,-16.0
219526,Shot Chart Detail,22401217,672,1629673,Jordan Poole,1610612764,Washington Wizards,4,1,20,...,C. Carrington,1642267.0,2.0,NaN,NaN,NaN,NaN,22401217.0,-14.0,-14.0