# Data Wrangling

Load & transform NBA dataset

Ensure the two datasets are located in folder called data (or update load filepath)

### Import & Load Data

In [27]:
# Imports
import pandas as pd
import polars as pl
import numpy as np
import seaborn as sns
import statsmodels.api as sm
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder, OneHotEncoder

In [58]:
# Load raw csv data
df_shots = pl.read_csv("../data/shotdetail_2024.csv", try_parse_dates=True)
df_cdnnba = pl.read_csv("../data/cdnnba_2024.csv", try_parse_dates=True)

# Merge cdnnba & shots dataframes
df_merged = df_shots.join(df_cdnnba, how='left', left_on=['GAME_ID', 'GAME_EVENT_ID'], right_on=['gameId', 'actionNumber'])
df_merged = df_merged.with_columns(pl.concat_str([pl.col('GAME_ID'), pl.col('GAME_EVENT_ID')], separator="_").alias('Record_Id'))

### Exploration

In [23]:
df_merged.dtypes

[String,
 Int64,
 Int64,
 Int64,
 String,
 Int64,
 String,
 Int64,
 Int64,
 Int64,
 String,
 String,
 String,
 String,
 String,
 String,
 Int64,
 Int64,
 Int64,
 Int64,
 Int64,
 Int64,
 String,
 String,
 String,
 Datetime(time_unit='us', time_zone='UTC'),
 Int64,
 String,
 String,
 String,
 String,
 Int64,
 Float64,
 Float64,
 Int64,
 Int64,
 Int64,
 Datetime(time_unit='us', time_zone='UTC'),
 Int64,
 Boolean,
 Int64,
 Int64,
 Int64,
 String,
 String,
 String,
 Int64,
 String,
 String,
 String,
 Int64,
 String,
 String,
 String,
 Int64,
 String,
 Int64,
 String,
 String,
 Float64,
 String,
 String,
 Int64,
 Int64,
 Int64,
 Int64,
 Int64,
 Int64,
 Int64,
 String,
 Int64,
 Int64,
 String,
 Int64,
 Int64,
 Int64,
 Int64,
 String,
 Int64,
 String]

In [24]:
df_merged.describe()

shape: (9, 81)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ GRID_TYPE ┆ GAME_ID   ┆ GAME_EVEN ┆ … ┆ foulTechn ┆ foulDrawn ┆ foulDrawn ┆ Record_I │
│ ---       ┆ ---       ┆ ---       ┆ T_ID      ┆   ┆ icalTotal ┆ PlayerNam ┆ PersonId  ┆ d        │
│ str       ┆ str       ┆ f64       ┆ ---       ┆   ┆ ---       ┆ e         ┆ ---       ┆ ---      │
│           ┆           ┆           ┆ f64       ┆   ┆ f64       ┆ ---       ┆ f64       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 219527    ┆ 219527.0  ┆ 219527.0  ┆ … ┆ 0.0       ┆ 0         ┆ 0.0       ┆ 219527   │
│ null_coun ┆ 0         ┆ 0.0       ┆ 0.0       ┆ … ┆ 219527.0  ┆ 219527    ┆ 219527.0  ┆ 0        │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ 2.2401e7  ┆ 330.56749 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆           ┆ 3         ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ null      ┆ 354.58010 ┆ 199.05874 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 3         ┆ 2         ┆   ┆           ┆           ┆           ┆          │
│ min       ┆ Shot      ┆ 2.2400001 ┆ 4.0       ┆ … ┆ null      ┆ null      ┆ null      ┆ 22400001 │
│           ┆ Chart     ┆ e7        ┆           ┆   ┆           ┆           ┆           ┆ _10      │
│           ┆ Detail    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ null      ┆ 2.240031e ┆ 157.0     ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 7         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 50%       ┆ null      ┆ 2.2400618 ┆ 329.0     ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ e7        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 75%       ┆ null      ┆ 2.2400923 ┆ 498.0     ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ e7        ┆           ┆   ┆           ┆           ┆           ┆          │
│ max       ┆ Shot      ┆ 2.240123e ┆ 851.0     ┆ … ┆ null      ┆ null      ┆ null      ┆ 22401230 │
│           ┆ Chart     ┆ 7         ┆           ┆   ┆           ┆           ┆           ┆ _98      │
│           ┆ Detail    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Data Cleaning

In [ ]:
# Convert data types
df_merged = df_merged.with_columns(
    pl.col('GAME_DATE').cast(pl.String).str.to_datetime(format="%Y%m%d").alias('game_date'),
    pl.when(pl.col('HTM') == pl.col('teamTricode')).then(1).otherwise(0).alias('isHomeTeam'),
    pl.duration(minutes=pl.col('MINUTES_REMAINING'), seconds=pl.col('SECONDS_REMAINING')).alias('time_remaining'),
    (pl.col('scoreHome') - pl.col('scoreAway')).alias('score_margin_after'),
    pl.when(pl.col('SHOT_MADE_FLAG') == 1).then(
        pl.when(pl.col('actionType') == "3pt").then(pl.lit(3)).otherwise(pl.lit(2))
        ).otherwise(pl.lit(0)).alias('score_change'), 
    pl.when(pl.col('shotDistance').is_null()).then(pl.col('SHOT_DISTANCE')).otherwise(pl.col('shotDistance')).alias('shotDistance')
)

# Convert score to be relative to player taking actions perspective
df_merged = df_merged.with_columns(
    pl.when(pl.col('teamTricode') == pl.col('HTM'))
        .then(pl.col('score_margin_after') - pl.col('score_change'))
    .otherwise(pl.col('score_margin_after')*-1 - pl.col('score_change')).alias('relative_margin_before')
)

In [47]:
df_merged.head(5)

shape: (5, 86)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ GRID_TYPE ┆ GAME_ID  ┆ GAME_EVEN ┆ PLAYER_ID ┆ … ┆ time_rema ┆ score_mar ┆ score_cha ┆ relative_ │
│ ---       ┆ ---      ┆ T_ID      ┆ ---       ┆   ┆ ining     ┆ gin_after ┆ nge       ┆ margin_be │
│ str       ┆ i64      ┆ ---       ┆ i64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ fore      │
│           ┆          ┆ i64       ┆           ┆   ┆ duration[ ┆ i64       ┆ i32       ┆ ---       │
│           ┆          ┆           ┆           ┆   ┆ μs]       ┆           ┆           ┆ i64       │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ Shot      ┆ 22400001 ┆ 7         ┆ 1642258   ┆ … ┆ 11m 43s   ┆ 0         ┆ 0         ┆ 0         │
│ Chart     ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Detail    ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Shot      ┆ 22400001 ┆ 10        ┆ 1630552   ┆ … ┆ 11m 38s   ┆ 0         ┆ 0         ┆ 0         │
│ Chart     ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Detail    ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Shot      ┆ 22400001 ┆ 21        ┆ 1630552   ┆ … ┆ 10m 50s   ┆ -3        ┆ 3         ┆ 0         │
│ Chart     ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Detail    ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Shot      ┆ 22400001 ┆ 34        ┆ 1630811   ┆ … ┆ 9m 47s    ┆ 0         ┆ 0         ┆ 0         │
│ Chart     ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Detail    ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Shot      ┆ 22400001 ┆ 36        ┆ 203991    ┆ … ┆ 9m 44s    ┆ -2        ┆ 2         ┆ 0         │
│ Chart     ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Detail    ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [12]:
# Confirm no mismatching data between event types & shot flags
made_shots_mismatch = df_merged.filter(
    (pl.col('EVENT_TYPE') =='Made Shot') & (pl.col('SHOT_ATTEMPTED_FLAG')!=1) & (pl.col('SHOT_MADE_FLAG')!=1)
)

missed_shots_mismatch = df_merged.filter(
    (pl.col('EVENT_TYPE') =='Missed Shot') & (pl.col('SHOT_ATTEMPTED_FLAG')!=1) & (pl.col('SHOT_MADE_FLAG')!=0)
)

In [52]:
# Drop redundant (i.e. duplicate) columns
df_combined = df_merged.drop(['period', 'personId', 'actionType', 'GAME_DATE', 'SHOT_DISTANCE', 'teamId'])

# Drop columns deemed not required
df_combined = df_combined.drop([
    'EVENT_TYPE',
    'MINUTES_REMAINING',
    'SECONDS_REMAINING',
    'foulPersonalTotal',
    'foulTechnicalTotal',
    'foulDrawnPlayerName',
    'foulDrawnPersonId',
    'area',
    'areaDetail',
    'shotResult',
    'officialId',
    'turnoverTotal',
    'stealPlayerName',
    'stealPersonId',
    'reboundTotal',
    'reboundDefensiveTotal',
    'reboundOffensiveTotal',
    'blockPlayerName',
    'blockPersonId',
    'jumpBallLostPlayerName',
    'jumpBallLostPersonId',
    'jumpBallWonPlayerName',
    'jumpBallWonPersonId', 
    'jumpBallRecoveredName',    
    'jumpBallRecoverdPersonId',
    'shotActionNumber', 
    'SHOT_ATTEMPTED_FLAG', 
    'playerName',
    'playerNameI', 
    'teamTricode', 
    'possession',
    'xLegacy',
    'yLegacy',
    'x',
    'y',
    'description',
    'personIdsFilter',
    'descriptor'
])
df_combined

shape: (219_527, 43)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ GRID_TYPE ┆ GAME_ID  ┆ GAME_EVEN ┆ PLAYER_ID ┆ … ┆ score_mar ┆ score_cha ┆ relative_ ┆ isHomeTea │
│ ---       ┆ ---      ┆ T_ID      ┆ ---       ┆   ┆ gin_after ┆ nge       ┆ margin_be ┆ m         │
│ str       ┆ i64      ┆ ---       ┆ i64       ┆   ┆ ---       ┆ ---       ┆ fore      ┆ ---       │
│           ┆          ┆ i64       ┆           ┆   ┆ i64       ┆ i32       ┆ ---       ┆ i32       │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ i64       ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ Shot      ┆ 22400001 ┆ 7         ┆ 1642258   ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
│ Chart     ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Detail    ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Shot      ┆ 22400001 ┆ 10        ┆ 1630552   ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
│ Chart     ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Detail    ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Shot      ┆ 22400001 ┆ 21        ┆ 1630552   ┆ … ┆ -3        ┆ 3         ┆ 0         ┆ 0         │
│ Chart     ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Detail    ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Shot      ┆ 22400001 ┆ 34        ┆ 1630811   ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
│ Chart     ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Detail    ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Shot      ┆ 22400001 ┆ 36        ┆ 203991    ┆ … ┆ -2        ┆ 2         ┆ 0         ┆ 0         │
│ Chart     ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Detail    ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ Shot      ┆ 22401217 ┆ 643       ┆ 1629673   ┆ … ┆ -15       ┆ 2         ┆ -17       ┆ 1         │
│ Chart     ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Detail    ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Shot      ┆ 22401217 ┆ 646       ┆ 1629673   ┆ … ┆ -18       ┆ 0         ┆ -18       ┆ 1         │
│ Chart     ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Detail    ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Shot      ┆ 22401217 ┆ 661       ┆ 1642259   ┆ … ┆ -18       ┆ 3         ┆ -21       ┆ 1         │
│ Chart     ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Detail    ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Shot      ┆ 22401217 ┆ 668       ┆ 1630551   ┆ … ┆ -16       ┆ 2         ┆ -18       ┆ 1         │
│ Chart     ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Detail    ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Shot      ┆ 22401217 ┆ 672       ┆ 1629673   ┆ … ┆ -14       ┆ 2         ┆ -16       ┆ 1         │
│ Chart     ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Detail    ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

## Missing Data

Deal with null, NaN data

In [ ]:
# Replace nulls in pointsTotal & shotDistance with 0 - effectively what null means in this column
df_combined = df_combined.with_columns(
    pl.col('pointsTotal').fill_null(0).alias('pointsTotal')TotaT asdfasdfadsfasdfatest
)

shape: (0, 43)
┌───────────┬─────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ GRID_TYPE ┆ GAME_ID ┆ GAME_EVENT ┆ PLAYER_ID ┆ … ┆ score_mar ┆ score_cha ┆ relative_ ┆ isHomeTea │
│ ---       ┆ ---     ┆ _ID        ┆ ---       ┆   ┆ gin_after ┆ nge       ┆ margin_be ┆ m         │
│ str       ┆ i64     ┆ ---        ┆ i64       ┆   ┆ ---       ┆ ---       ┆ fore      ┆ ---       │
│           ┆         ┆ i64        ┆           ┆   ┆ i64       ┆ i32       ┆ ---       ┆ i32       │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ i64       ┆           │
╞═══════════╪═════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
└───────────┴─────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

Drop null values

In [ ]:
# Drop records with null values for scoreAway or ScoreHome
df_combined = df_combined.drop_nulls('score_margin_after')

df_nulls = df_combined.filter(pl.col('relative_margin_before').is_null() | pl.col('LOC_Y').is_null())
test = df_combined.filter(pl.col('relative_margin_before') == 0)

df_nulls

In [56]:
df_combined.columns

['GRID_TYPE',
 'GAME_ID',
 'GAME_EVENT_ID',
 'PLAYER_ID',
 'PLAYER_NAME',
 'TEAM_ID',
 'TEAM_NAME',
 'PERIOD',
 'ACTION_TYPE',
 'SHOT_TYPE',
 'SHOT_ZONE_BASIC',
 'SHOT_ZONE_AREA',
 'SHOT_ZONE_RANGE',
 'LOC_X',
 'LOC_Y',
 'SHOT_MADE_FLAG',
 'HTM',
 'VTM',
 'clock',
 'timeActual',
 'periodType',
 'subType',
 'qualifiers',
 'scoreHome',
 'scoreAway',
 'edited',
 'orderNumber',
 'isTargetScoreLastPeriod',
 'isFieldGoal',
 'side',
 'shotDistance',
 'pointsTotal',
 'assistPlayerNameInitial',
 'assistPersonId',
 'assistTotal',
 'Record_Id',
 'game_date',
 'atHome',
 'time_remaining',
 'score_margin_after',
 'score_change',
 'relative_margin_before',
 'isHomeTeam']

In [ ]:
# Subset of numeric columns for correlation
numerical = [
    'PERIOD',
    'LOC_X',
    'LOC_Y',
    'pointsTotal',
    'relative_margin_before',
    'shotDistance',
    'SHOT_MADE_FLAG',
    'time_remaining'
]

# Subset of columns including categorical variables only
categorical = [
    'ACTION_TYPE',
    'isHomeTeam',
    'PLAYER_ID',
    'SHOT_ZONE_BASIC',
    'SHOT_ZONE_AREA',
    'SHOT_ZONE_RANGE',
    'subType',
    'SHOT_MADE_FLAG'
]
    
# Subset of columns to be used in classifier models
classification = [   
    'PERIOD',
    'LOC_X',
    'LOC_Y',
    'pointsTotal',
    'relative_margin_before',
    'shotDistance',
    'SHOT_MADE_FLAG',
    'time_remaining'
]

df_numerical = df_combined.select(numerical)
df_categorical = df_combined.select(categorical)
df_model = df_combined.select(classification)

## Encoding

Encode categorical variables to enable use in classifiers

In [ ]:
df_encoded = df_combined.select(classification).to_dummies(
    ['subType',
     'side',
     'SHOT_ZONE_BASIC',
     'SHOT_ZONE_AREA',
     'SHOT_ZONE_RANGE'
     ]
)
df_encoded

shape: (219_524, 14)
┌────────┬───────┬───────┬─────────────┬───┬───────────────┬───────────┬────────────┬──────────────┐
│ PERIOD ┆ LOC_X ┆ LOC_Y ┆ pointsTotal ┆ … ┆ subType_Layup ┆ side_left ┆ side_right ┆ time_remaini │
│ ---    ┆ ---   ┆ ---   ┆ ---         ┆   ┆ ---           ┆ ---       ┆ ---        ┆ ng           │
│ i64    ┆ i64   ┆ i64   ┆ i64         ┆   ┆ u8            ┆ u8        ┆ u8         ┆ ---          │
│        ┆       ┆       ┆             ┆   ┆               ┆           ┆            ┆ duration[μs] │
╞════════╪═══════╪═══════╪═════════════╪═══╪═══════════════╪═══════════╪════════════╪══════════════╡
│ 1      ┆ -168  ┆ 205   ┆ 0           ┆ … ┆ 0             ┆ 1         ┆ 0          ┆ 11m 43s      │
│ 1      ┆ -136  ┆ -1    ┆ 0           ┆ … ┆ 0             ┆ 1         ┆ 0          ┆ 11m 38s      │
│ 1      ┆ 157   ┆ 203   ┆ 3           ┆ … ┆ 0             ┆ 1         ┆ 0          ┆ 10m 50s      │
│ 1      ┆ -176  ┆ 184   ┆ 0           ┆ … ┆ 0             ┆ 1         ┆ 0          ┆ 9m 47s       │
│ 1      ┆ -25   ┆ 8     ┆ 2           ┆ … ┆ 1             ┆ 1         ┆ 0          ┆ 9m 44s       │
│ …      ┆ …     ┆ …     ┆ …           ┆ … ┆ …             ┆ …         ┆ …          ┆ …            │
│ 4      ┆ 15    ┆ 1     ┆ 18          ┆ … ┆ 1             ┆ 1         ┆ 0          ┆ 3m 14s       │
│ 4      ┆ 183   ┆ 267   ┆ 0           ┆ … ┆ 0             ┆ 1         ┆ 0          ┆ 2m 53s       │
│ 4      ┆ 229   ┆ 32    ┆ 14          ┆ … ┆ 0             ┆ 1         ┆ 0          ┆ 2m 11s       │
│ 4      ┆ -7    ┆ 14    ┆ 13          ┆ … ┆ 0             ┆ 1         ┆ 0          ┆ 1m 45s       │
│ 4      ┆ 17    ┆ 17    ┆ 20          ┆ … ┆ 1             ┆ 1         ┆ 0          ┆ 1m 20s       │
└────────┴───────┴───────┴─────────────┴───┴───────────────┴───────────┴────────────┴──────────────┘

In [ ]:
pddf_model = df_model.to_pandas()