# Group Project Dataset EDA

Exploratory data analysis of selected datasets from data.gov

In [2]:
import pandas as pd
import seaborn as sns

In [3]:

df= pd.read_csv("data/toiletmapexport_250801_074429.csv")
df.head(10)

,FacilityID,URL,Name,FacilityType,Address1,Town,State,AddressNote,Latitude,Longitude,...,Ambulant,Accessible,LHTransfer,RHTransfer,ToiletNote,SharpsDisposal,DrinkingWater,SanitaryDisposal,MensPadDisposal,Shower
0,1,https://toiletmap.gov.au/facility/1,Sandy Beach Reserve,Park or reserve,"Lost 15525, West Road",Bassendean,WA,NaN,-31.921836,115.950206,...,False,True,False,False,NaN,True,True,True,False,False
1,2,https://toiletmap.gov.au/facility/2,Point Reserve,Park or reserve,"Lot 197, North Road",Bassendean,WA,NaN,-31.904410,115.960991,...,False,True,False,False,NaN,True,True,True,False,False
2,3,https://toiletmap.gov.au/facility/3,Success Hill Reserve,Park or reserve,"Lot 2838, Seventh Avenue",Bassendean,WA,NaN,-31.896289,115.955781,...,False,True,False,False,NaN,True,True,True,False,True
3,4,https://toiletmap.gov.au/facility/4,Jubilee Reserve,Park or reserve,"Lot 6322, Robinson Road",Eden Hill,WA,NaN,-31.891474,115.940164,...,False,False,False,False,NaN,True,False,True,False,False
4,5,https://toiletmap.gov.au/facility/5,Ashfield Reserve,Park or reserve,"Lot 12061, 2 Coulston Road",Ashfield,WA,NaN,-31.913433,115.936477,...,False,True,False,False,NaN,True,True,True,False,False
5,7,https://toiletmap.gov.au/facility/7,Mary Crescent Reserve,Park or reserve,Mary Crescent,Eden Hill,WA,NaN,-31.890366,115.948090,...,False,True,False,False,NaN,True,True,True,False,False
6,9,https://toiletmap.gov.au/facility/9,Bassendean Oval West,Sporting facility,"Lot 246, Old Perth Road",Bassendean,WA,NaN,-31.903716,115.956490,...,False,False,False,False,NaN,False,False,False,False,False
7,15,https://toiletmap.gov.au/facility/15,Apex Park,Park or reserve,Moranbah Access Road,Moranbah,QLD,NaN,-22.014444,148.045242,...,False,False,False,False,NaN,False,False,False,False,False
8,16,https://toiletmap.gov.au/facility/16,Lions Park,Park or reserve,12 Belyando Avenue,Moranbah,QLD,NaN,-21.999341,148.043973,...,False,False,False,False,NaN,False,False,False,False,False
9,17,https://toiletmap.gov.au/facility/17,Parella Street,Park or reserve,Parella Street,Moranbah,QLD,NaN,-22.000152,148.048616,...,False,True,False,False,NaN,False,False,False,False,True

In [ ]:
df.info()

# Note - data dictionary seems to have all listed as text strings

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24715 entries, 0 to 24714
Data columns (total 47 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   FacilityID         24715 non-null  int64
 1   URL                24715 non-null  object
 2   Name               24715 non-null  object
 3   FacilityType       24715 non-null  object
 4   Address1           24623 non-null  object
 5   Town               24714 non-null  object
 6   State              24714 non-null  object
 7   AddressNote        2667 non-null   object
 8   Latitude           24715 non-null  float64
 9   Longitude          24715 non-null  float64
 10  Parking            24715 non-null  bool
 11  ParkingAccessible  24715 non-null  bool
 12  ParkingNote        1914 non-null   object
 13  KeyRequired        24715 non-null  bool
 14  MLAK24             24715 non-null  bool
 15  MLAKAfterHours     24715 non-null  bool
 16  PaymentRequired    24715 non-null  bool
 17  AccessNote         1873 non-null   object
 18  AdultChange        24715 non-null  bool
 19  ChangingPlaces     24715 non-null  bool
 20  BYOSling           24715 non-null  bool
 21  ACShower           24715 non-null  bool
 22  ACMLAK             24715 non-null  bool
 23  AdultChangeNote    153 non-null    object
 24  BabyChange         24715 non-null  bool
 25  BabyCareRoom       24715 non-null  bool
 26  BabyChangeNote     227 non-null    object
 27  DumpPoint          24715 non-null  bool
 28  DPWashout          24715 non-null  bool
 29  DPAfterHours       24715 non-null  bool
 30  DumpPointNote      240 non-null    object
 31  OpeningHours       24715 non-null  object
 32  OpeningHoursNote   3391 non-null   object
 33  Male               24715 non-null  bool
 34  Female             24715 non-null  bool
 35  Unisex             24715 non-null  bool
 36  AllGender          24715 non-null  bool
 37  Ambulant           24715 non-null  bool
 38  Accessible         24715 non-null  bool
 39  LHTransfer         24715 non-null  bool
 40  RHTransfer         24715 non-null  bool
 41  ToiletNote         4598 non-null   object
 42  SharpsDisposal     24715 non-null  bool
 43  DrinkingWater      24715 non-null  bool
 44  SanitaryDisposal   24715 non-null  bool
 45  MensPadDisposal    24715 non-null  bool
 46  Shower             24715 non-null  bool
dtypes: bool(29), float64(2), int64(1), object(15)
memory usage: 4.1+ MB

In [5]:
df.shape

(24715, 47)

In [5]:
df.isna().sum()

FacilityID               0
URL                      0
Name                     0
FacilityType             0
Address1                92
Town                     1
State                    1
AddressNote          22048
Latitude                 0
Longitude                0
Parking                  0
ParkingAccessible        0
ParkingNote          22801
KeyRequired              0
MLAK24                   0
MLAKAfterHours           0
PaymentRequired          0
AccessNote           22842
AdultChange              0
ChangingPlaces           0
BYOSling                 0
ACShower                 0
ACMLAK                   0
AdultChangeNote      24562
BabyChange               0
BabyCareRoom             0
BabyChangeNote       24488
DumpPoint                0
DPWashout                0
DPAfterHours             0
DumpPointNote        24475
OpeningHours             0
OpeningHoursNote     21324
Male                     0
Female                   0
Unisex                   0
AllGender                0
Ambulant                 0
Accessible               0
LHTransfer               0
RHTransfer               0
ToiletNote           20117
SharpsDisposal           0
DrinkingWater            0
SanitaryDisposal         0
MensPadDisposal          0
Shower                   0
dtype: int64

In [8]:
df.columns

Index(['FacilityID', 'URL', 'Name', 'FacilityType', 'Address1', 'Town',
       'State', 'AddressNote', 'Latitude', 'Longitude', 'Parking',
       'ParkingAccessible', 'ParkingNote', 'KeyRequired', 'MLAK24',
       'MLAKAfterHours', 'PaymentRequired', 'AccessNote', 'AdultChange',
       'ChangingPlaces', 'BYOSling', 'ACShower', 'ACMLAK', 'AdultChangeNote',
       'BabyChange', 'BabyCareRoom', 'BabyChangeNote', 'DumpPoint',
       'DPWashout', 'DPAfterHours', 'DumpPointNote', 'OpeningHours',
       'OpeningHoursNote', 'Male', 'Female', 'Unisex', 'AllGender', 'Ambulant',
       'Accessible', 'LHTransfer', 'RHTransfer', 'ToiletNote',
       'SharpsDisposal', 'DrinkingWater', 'SanitaryDisposal',
       'MensPadDisposal', 'Shower'],
      dtype='object')

In [11]:
df_clean = df.drop(labels=['AddressNote', 'ParkingNote', 'AccessNote', 'AdultChangeNote'], axis=1)
df_clean.head(10)

,FacilityID,URL,Name,FacilityType,Address1,Town,State,Latitude,Longitude,Parking,...,Ambulant,Accessible,LHTransfer,RHTransfer,ToiletNote,SharpsDisposal,DrinkingWater,SanitaryDisposal,MensPadDisposal,Shower
0,1,https://toiletmap.gov.au/facility/1,Sandy Beach Reserve,Park or reserve,"Lost 15525, West Road",Bassendean,WA,-31.921836,115.950206,False,...,False,True,False,False,NaN,True,True,True,False,False
1,2,https://toiletmap.gov.au/facility/2,Point Reserve,Park or reserve,"Lot 197, North Road",Bassendean,WA,-31.904410,115.960991,False,...,False,True,False,False,NaN,True,True,True,False,False
2,3,https://toiletmap.gov.au/facility/3,Success Hill Reserve,Park or reserve,"Lot 2838, Seventh Avenue",Bassendean,WA,-31.896289,115.955781,True,...,False,True,False,False,NaN,True,True,True,False,True
3,4,https://toiletmap.gov.au/facility/4,Jubilee Reserve,Park or reserve,"Lot 6322, Robinson Road",Eden Hill,WA,-31.891474,115.940164,False,...,False,False,False,False,NaN,True,False,True,False,False
4,5,https://toiletmap.gov.au/facility/5,Ashfield Reserve,Park or reserve,"Lot 12061, 2 Coulston Road",Ashfield,WA,-31.913433,115.936477,True,...,False,True,False,False,NaN,True,True,True,False,False
5,7,https://toiletmap.gov.au/facility/7,Mary Crescent Reserve,Park or reserve,Mary Crescent,Eden Hill,WA,-31.890366,115.948090,True,...,False,True,False,False,NaN,True,True,True,False,False
6,9,https://toiletmap.gov.au/facility/9,Bassendean Oval West,Sporting facility,"Lot 246, Old Perth Road",Bassendean,WA,-31.903716,115.956490,False,...,False,False,False,False,NaN,False,False,False,False,False
7,15,https://toiletmap.gov.au/facility/15,Apex Park,Park or reserve,Moranbah Access Road,Moranbah,QLD,-22.014444,148.045242,True,...,False,False,False,False,NaN,False,False,False,False,False
8,16,https://toiletmap.gov.au/facility/16,Lions Park,Park or reserve,12 Belyando Avenue,Moranbah,QLD,-21.999341,148.043973,True,...,False,False,False,False,NaN,False,False,False,False,False
9,17,https://toiletmap.gov.au/facility/17,Parella Street,Park or reserve,Parella Street,Moranbah,QLD,-22.000152,148.048616,True,...,False,True,False,False,NaN,False,False,False,False,True

In [ ]:
# Records with blank values
df.isna().any(axis=1).sum()
df_clean.isna().any(axis=1).sum()

24715

In [13]:
df['State'].value_counts()

State
NSW    7732
VIC    5878
QLD    4600
WA     2785
SA     2093
TAS     980
NT      325
ACT     321
Name: count, dtype: int64

In [ ]:
sns.pairplot(df)

Error in callback <function _draw_all_if_interactive at 0x0000017D562F0C20> (for post_execute), with arguments args (),kwargs {}:

KeyboardInterrupt: